### ISSUE TITLE
Link isn't working

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/Website#1]
gives 502 error

**Comment by MCUnderground** [comment]
Ik, it is shut down :/

**Comment by jasonwynn10** [comment]
Who's hosting it? From where?

**Comment by jasonwynn10** [comment]
I made a new one here: LostTeam.Github.io

**Comment by jasonwynn10** [comment]
We could convert to github's website hosting with Github Pages. It works better and we can customize it more.

**Comment by jasonwynn10** [comment]
This Website is outdated, this  repo should be removed if it's unused.
